name: A test workflow

on: [push]

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Show memory
      run: free -h
    - name: List disk
      run: lsblk
    - name: Show cpus
      run: lscpu
